//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazılımMuhendisligi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uygarEntities : DbContext
    {
        public uygarEntities()
            : base("name=uygarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bill> bill { get; set; }
        public DbSet<campaign> campaign { get; set; }
        public DbSet<hotel> hotel { get; set; }
        public DbSet<hotelreservation> hotelreservation { get; set; }
        public DbSet<location> location { get; set; }
        public DbSet<transportationservice> transportationservice { get; set; }
        public DbSet<travelcompany> travelcompany { get; set; }
        public DbSet<uuser> uuser { get; set; }
    }
}
